name = "landing-api"
main = "src/index.js"
compatibility_date = "2024-12-01"
account_id = "3bd5bc5bc00020cde41d7070de85cb6e"

routes = [
  { pattern = "planetdb.co.kr/api/*", zone_name = "planetdb.co.kr" }
]

[[d1_databases]]
binding = "DB"
database_name = "landing-db"
database_id = "7a9087b0-554c-4678-a5a9-a5d60c3fe20e"

[vars]
SHEET_ID = "11MKLOt1BwPG-cXKohjaCTZdgda3aw85Z6irEiFufxdw"
SHEET_NAME = "오렌지플래닛"
ALLOWED_ORIGIN = "*"
